# Getting Started with Front/Climate Data

The intention with this information and scripts is to provide a basic understanding of how you can use **CDO** to speed-up your **netCDF** file data manipulation. [More info go directly to the Max Planck Institute CDO website](https://code.mpimet.mpg.de/projects/cdo/)

## Installation Process

### **MacOS**

Follow the instruction and downloaded **MacPorts**. **MacPorts** is an open-source community initiative to design an easy-to-use system for compiling, installing, and upgrading the command-line on the Mac operating system.

[MacPorts website](https://www.macports.org/index.php) [MacPorts download](https://www.macports.org/install.php)

After the installation (if you have admin rights) open the terminal and type:

`port install cdo`

If you don't have admin rights, open the terminal and type:

`sudo port install cdo` and write your password

### **Windows 10**

In the current windows 10 version(s) Microsoft includes an Ubuntu 16.04 LTS embedded Linux. This environment offers a clean integration with the windows file systems and and the opportunity to install CDO via the native package manager of Ubuntu.

Install the Ubuntu app from the Microsoft Store application. Then open the Ubuntu terminal and type:

`sudo apt-get install cdo` and write your password

### **Linux**

For Linux go to: [Linux](https://code.mpimet.mpg.de/projects/cdo/wiki/Linux_Platform)

## Ncview: a netCDF visual browser

Ncview is quick visual browser that allows you to explore **netCDF** files very easily: `ncview`. `ncview` is an easy to use netCDF file viewer for **linux** and **OS X**. It can read any netCDF file.

To install **ncview**, open the terminal and type:

-   **OS X**: `port install ncview`
-   **Linux**: `sudo apt-get install ncview`
